### ISSUE TITLE
Real speed movies should flow without pauses

### ISSUE THREAD

**Issue by DanielBarstow** [windows-on-earth/winearth-webui#46]
Real speed movies, such as ISS028-E-30545-30645, should flow like a movie, instead of showing one image for a while, then jumping to the next.

You had this working before, I believe using FFMPEG (?).  It worked, though it had some fuzziness in the flow.  so, we asked Amy Gooch to develop a better method.  She couldn't develop it in time, so you should go back to the original FFMPEG method you had working before.

**Comment by AlexNguyenJJ** [comment]
Hi Dan,

Real speed movies were created by taking the collection of images in a time lapse and then showing them together with the same interval that the time lapse was originally captured in. If it should flow like a movie, then I am unsure what the difference is between "real speed" and "fast".

**Comment by AlexNguyenJJ** [comment]
Kevin is traveling this week, and will respond when he is back.

**Comment by kevincoakley** [comment]
See https://github.com/windows-on-earth/winearth-webui/issues/28
